replicaCount: 2

ingress:
  host: noteflow.example.com
  tls:
    secretName: noteflow-production-tls

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

existingSecret: noteflow-production-secrets
